#include "Candidate.h"




void Candidate::addVoter(Person& aVoter)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B81 begin
{
}
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B81 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Candidate::getAverageAge()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B85 begin
{
    return 0;
}
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B85 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Candidate::getAverageSalary()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B87 begin
{
    return 0.0;
}
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B87 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Candidate::operator<(Candidate& aCandidate, Candidate& bCandidate)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B89 begin
{
    return false;
}
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B89 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Candidate::candidates()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B90 begin
{
    return 0;
}
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B90 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Candidate::printInfo()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B9F begin
{
}
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B9F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
