#include "Person.h"




void Person::setAge(int newAge)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B4F begin
{
}
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B4F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Person::setSalary(double newSalary)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B51 begin
{
}
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B51 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Person::printInfo()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B53 begin
{
}
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B53 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
