#include "PersonSet.h"




void PersonSet::addElement(Person& person)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104-514a8018:154236ec350:-8000:0000000000000D15 begin
{
}
// section -64--88-1-104-514a8018:154236ec350:-8000:0000000000000D15 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Person* PersonSet::removeElement()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104-514a8018:154236ec350:-8000:0000000000000D19 begin
{
}
// section -64--88-1-104-514a8018:154236ec350:-8000:0000000000000D19 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Person& PersonSet::nextElement()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104-514a8018:154236ec350:-8000:0000000000000D1C begin
{
}
// section -64--88-1-104-514a8018:154236ec350:-8000:0000000000000D1C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void PersonSet::reStore(int index)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104-514a8018:154236ec350:-8000:0000000000000D1E begin
{
}
// section -64--88-1-104-514a8018:154236ec350:-8000:0000000000000D1E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Person* PersonSet::removeElement(int Index)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104-514a8018:154236ec350:-8000:0000000000000D21 begin
{
}
// section -64--88-1-104-514a8018:154236ec350:-8000:0000000000000D21 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
