#include "Voter.h"




double Voter::voters()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B78 begin
{
    return 0.0;
}
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B78 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Person& Voter::selectCandidate(PersonSet& candidates)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B7A begin
{
}
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B7A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Voter::vote(Candidate& aCandidate)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B7E begin
{
}
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B7E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Voter::printInfo()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B9D begin
{
}
// section -64--88-1-104--436fb044:15421dd3036:-8000:0000000000000B9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
